<?php

function title_system($field){
  $system["description"] = t("Enables users to link to stories, articles or similar content by title.");
  return $system[$field];
}


function title_page() {
  global $theme;
  page_header();
  if (user_access("access content")) {

    $title = arg(1);

    $number = ($title ? db_num_rows(db_query("SELECT nid FROM node WHERE title = '%s' AND status = 1", $title)) : 1);

    if ($number > 1) {
      $result = db_query("SELECT n.*, u.name, u.uid FROM node n LEFT JOIN users u ON n.uid = u.uid WHERE n.title = '%s' AND n.status = 1 ORDER BY created DESC", $title);

      while ($node = db_fetch_object($result)) {
        if (node_access("view", $node)) {
          $output .= "<p><b>". l($node->title, array("id" => $node->nid)) ."</b><br /><small>$node->type - ". format_name($node) ." - ". format_date($node->ccreated, "small") ."</small></p>";
        }
      }

      $theme->header();
      $theme->box(t("Result"), $output);
      $theme->footer();
    }
    elseif ($number) {
      $node = ($title ? node_load(array("title" => $title, "status" => 1)) : node_load(array("status" => 1, "nid" => ($edit["id"] ? $edit["id"] : $id))));
      if (node_access("view", $node)) {
        if (isset($revision)) {
          $node = $node->revisions[$revision]["node"];
        }
        $theme->header();
        node_view($node);
        $theme->footer();
      }
      else {
        title_failure();
      }

    } 
    else {
      title_failure();
    }

  }
  else {
    $theme->header();
    $theme->box(t("Access denied"), message_access());
    $theme->footer();
  }
}

function title_failure() {
  global $theme;
  $theme->header();
  $theme->box(t("Not found"), t("The node you are looking for does no longer exist or is not accessible without the proper access rights.") ."\n");
  $theme->footer();
}

?>
